name = "yggdrasil"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "ygg-db"
database_id = "ygg-db"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "ygg-storage"
