name = "yggdrasil"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 关键配置：保持在 Cloudflare Dashboard 控制台设置的环境变量与 Secrets 不被部署覆盖删除
keep_vars = true

[vars]
APP_NAME = "Yggdrasil"
ADMIN_PASSWORD = "admin"
JWT_SECRET = "ygg_jwt_secret_default_2026"
